### ISSUE TITLE
HTML markup not shown correctly

### ISSUE THREAD

**Issue by adamhradil** [keombre/progtest-theme#37]
In latest lecture task markup picks up wrong words.
![Screenshot_66](https://user-images.githubusercontent.com/24945561/100136057-cc20d380-2e8a-11eb-9365-b8cc40c335ed.png)

**Comment by keombre** [comment]
Sorry, but I won't fix this.
Progtest contains code samples in C, Java, Bash, EBNF or any structured text.
We use highlight.js to try and guess the correct language, but it isn't 100% reliable.

There is currently no way to reliably determine the language (without an ever-expanding list of edge cases).
Since the assignment contents are stored in plain HTML it is up to the teachers (usually the course guarantor) to label the code samples with HTML tags.
I personally, however, don't think that any teacher will start marking their code since it has no visible benefit in the original Progtest.
